FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    "mlflow==2.11.0" \
    "scikit-learn==1.4.0" \
    "pandas==2.2.0" \
    "numpy==1.26.4" \
    "boto3==1.34.0"

COPY src/train.py .

CMD ["python", "train.py"]